# GRPO Training Configuration
# Converted directly from CLI invocation
# Full-scale run (not a debug config)

# ==============================================================================
# Model Configuration
# ==============================================================================
model:
  path: "Qwen/Qwen2.5-1.5B-Instruct"
  use_remove_padding: true
  enable_gradient_checkpointing: true

# ==============================================================================
# Data Configuration
# ==============================================================================
data:
  train_files: "data/gsm8k/train_sample.parquet"
  val_files: "data/gsm8k/val_sample.parquet"
  train_batch_size: 1024
  max_prompt_length: 512
  max_response_length: 1024
  filter_overlong_prompts: true
  truncation: "error"

# ==============================================================================
# Algorithm Configuration
# ==============================================================================
algorithm:
  adv_estimator: "grpo"
  use_kl_in_reward: false

# ==============================================================================
# Actor / Rollout / Reference Configuration
# ==============================================================================
actor_rollout_ref:

  model:
    path: "Qwen/Qwen2.5-1.5B-Instruct"
    use_remove_padding: true
    enable_gradient_checkpointing: true

  actor:
    optim:
      lr: 1.0e-6

    ppo_mini_batch_size: 16
    ppo_micro_batch_size_per_gpu: 16

    use_kl_loss: true
    kl_loss_coef: 0.001
    kl_loss_type: "low_var_kl"
    entropy_coeff: 0.0

    fsdp_config:
      param_offload: false
      optimizer_offload: false

  rollout:
    name: "vllm"
    tensor_model_parallel_size: 2
    gpu_memory_utilization: 0.6
    n: 5
    log_prob_micro_batch_size_per_gpu: 16

  ref:
    log_prob_micro_batch_size_per_gpu: 16
    fsdp_config:
      param_offload: true

# ==============================================================================
# Trainer Configuration
# ==============================================================================
trainer:
  critic_warmup: 0

  # Logging
  logger: ['console', 'wandb']  # Console and wandb for monitoring
  project_name: "verl_grpo_example_gsm8k"
  experiment_name: "verl_grpo_example_gsm8k"  # Timestamp will be added automatically
  default_local_dir: "checkpoints/verl_grpo_example_gsm8k"

  project_name: "verl_grpo_example_gsm8k"
  experiment_name: "verl_grpo_example_gsm8k"

  n_gpus_per_node: 8
  nnodes: 1

  save_freq: 20
  test_freq: 5
  total_epochs: 15
