"""
Custom GSM8K reward function compatible with verl's RewardManager.

This module defines a single entrypoint function `compute_score` that
verl will call when `custom_reward_function.path` points here.
"""

from __future__ import annotations

import re
from typing import Any, Dict, Optional

_SOLUTION_CLIP_CHARS = 300


def _extract_solution(solution_str: str, method: str = "strict") -> Optional[str]:
    """
    Extract the final numeric answer from the model output.

    Parameters
    ----------
    solution_str :
        The full text generated by the model.
    method :
        Extraction mode. If "strict", require a pattern like
        "#### 72". If "flexible", return the last numeric token.

    Returns
    -------
    Optional[str]
        The extracted answer string without commas or "$", or
        None if no valid answer is found.
    """
    assert method in {"strict", "flexible"}

    text = solution_str
    if len(text) > _SOLUTION_CLIP_CHARS:
        text = text[-_SOLUTION_CLIP_CHARS :]

    if method == "strict":
        # Look for: #### -123.45
        matches = re.findall(r"#### (\-?[0-9\.,]+)", text)
        if not matches:
            return None
        final = matches[-1]
        return final.replace(",", "").replace("$", "")

    # Flexible: take the last reasonable number in the text
    candidates = re.findall(r"(\-?[0-9\.,]+)", text)
    if not candidates:
        return None

    invalid = {"", "."}
    for candidate in reversed(candidates):
        if candidate not in invalid:
            return candidate.replace(",", "").replace("$", "")

    return None


def compute_score(
    data_source: str,
    solution_str: str,
    ground_truth: str,
    extra_info: Optional[Dict[str, Any]] = None,
) -> float:
    """
    Compute a scalar reward for a single GSM8K example.

    This function matches verl's expected signature for custom reward
    functions. It returns 1.0 for a correct answer and 0.0 otherwise.

    Parameters
    ----------
    data_source :
        Name of the dataset. Ignored here but required by the API.
    solution_str :
        The model-generated solution text.
    ground_truth :
        The ground truth numeric answer, e.g. "72".
    extra_info :
        Optional extra fields from the DataProto. Unused.

    Returns
    -------
    float
        Reward in [0.0, 1.0]. 1.0 if the extracted answer matches
        the ground truth string exactly, otherwise 0.0.
    """
    # We do not need data_source or extra_info, but keep them for API compatibility.
    _ = data_source
    _ = extra_info

    answer = _extract_solution(solution_str=solution_str, method="strict")
    if answer is None:
        return 0.0

    return 1.0 if answer == ground_truth else 0.0
